## Database Config.
database:
  database: trackademia
  host: localhost
  port: 3306
  username: root
  password: alexuranium232
  # MariaDBAdapter, MySQLAdapter  <-  DBs available
  type: MySQLAdapter